language: java
jdk: openjdk11

services:
- docker

stages:
- name: test
  if: branch != master
- name: deployment
  if: branch = master AND type != pull_request

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
- echo "$DOCKER_PASSWORD" | docker login -u xnull --password-stdin bynull-docker-acinonyx.bintray.io

install: true

script:
- ./gradlew clean dockerPush -x test

notifications:
  email:
    recipients:
    - xrw.null@gmail.com
    on_success: never
    on_failure: always